config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :events
  resources :subscriptions
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # root 'events#index'
  root 'static_pages#index'

  get 'available_sailings', to: 'sailings#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many_attached :images
  has_one_attached :poster
  has_rich_text :text_en
  has_rich_text :text_ru

  has_many :videos
end

app/models/lyric.rb
class Lyric < ApplicationRecord
  has_rich_text :text
end

app/models/musician.rb
class Musician < ApplicationRecord
  belongs_to :admin, required: false
  has_one_attached :main_image

  validates :name_en, :name_ru, presence: true
  validates :name_ru, presence: true
  validates :full_name_en, presence: true
  validates :full_name_ru, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :event, required: false
  has_one_attached :videofile
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :info, :error, :warning
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @upcoming_events = Event.where('event_date_time > ?', DateTime.current)
    @upcoming = @upcoming_events.order(event_date_time: :asc).first
    @subscription = Subscription.new
  end

  # GET /events/1
  # GET /events/1.json
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:published, :event_date_time, :title_en, :title_ru)
  end
end

app/controllers/sailings_controller.rb
class SailingsController < ApplicationController
  def index
    @sailings = {
        "sailings": [
          {
            "origin_port": "CNSHA",
            "destination_port": "NLRTM",
            "departure_date": "2022-02-01",
            "arrival_date": "2022-03-01",
            "sailing_code": "ABCD"
          },
          {
            "origin_port": "CNSHA",
            "destination_port": "NLRTM",
            "departure_date": "2022-02-02",
            "arrival_date": "2022-03-02",
            "sailing_code": "EFGH"
          },
          {
            "origin_port": "CNSHA",
            "destination_port": "NLRTM",
            "departure_date": "2022-01-31",
            "arrival_date": "2022-02-28",
            "sailing_code": "IJKL"
          },
          {
            "origin_port": "CNSHA",
            "destination_port": "NLRTM",
            "departure_date": "2022-01-30",
            "arrival_date": "2022-03-05",
            "sailing_code": "MNOP"
          },
          {
            "origin_port": "CNSHA",
            "destination_port": "NLRTM",
            "departure_date": "2022-01-29",
            "arrival_date": "2022-02-15",
            "sailing_code": "QRST"
          },
          {
            "origin_port": "CNSHA",
            "destination_port": "ESBCN",
            "departure_date": "2022-01-29",
            "arrival_date": "2022-02-12",
            "sailing_code": "ERXQ"
          },
          {
            "origin_port": "ESBCN",
            "destination_port": "NLRTM",
            "departure_date": "2022-02-15",
            "arrival_date": "2022-03-29",
            "sailing_code": "ETRF"
          },
          {
            "origin_port": "ESBCN",
            "destination_port": "NLRTM",
            "departure_date": "2022-02-16",
            "arrival_date": "2022-02-20",
            "sailing_code": "ETRG"
          },
          {
            "origin_port": "ESBCN",
            "destination_port": "BRSSZ",
            "departure_date": "2022-02-16",
            "arrival_date": "2022-03-14",
            "sailing_code": "ETRB"
          }
        ],
        "rates": [
          {
            "sailing_code": "ABCD",
            "rate": "589.30",
            "rate_currency": "USD"
          },
          {
            "sailing_code": "EFGH",
            "rate": "890.32",
            "rate_currency": "EUR"
          },
          {
            "sailing_code": "IJKL",
            "rate": "97453",
            "rate_currency": "JPY"
          },
          {
            "sailing_code": "MNOP",
            "rate": "456.78",
            "rate_currency": "USD"
          },
          {
            "sailing_code": "QRST",
            "rate": "761.96",
            "rate_currency": "EUR"
          },
          {
            "sailing_code": "ERXQ",
            "rate": "261.96",
            "rate_currency": "EUR"
          },
          {
            "sailing_code": "ETRF",
            "rate": "70.96",
            "rate_currency": "USD"
          },
          {
            "sailing_code": "ETRG",
            "rate": "69.96",
            "rate_currency": "USD"
          },
          {
            "sailing_code": "ETRB",
            "rate": "439.96",
            "rate_currency": "USD"
          }
        ],
        "exchange_rates": {
          "2022-01-29": {
            "usd": 1.1138,
            "jpy": 130.85
          },
          "2022-01-30": {
            "usd": 1.1138,
            "jpy": 132.97
          },
          "2022-01-31": {
            "usd": 1.1156,
            "jpy": 131.2
          },
          "2022-02-01": {
            "usd": 1.126,
            "jpy": 130.15
          },
          "2022-02-02": {
            "usd": 1.1323,
            "jpy": 133.91
          },
          "2022-02-15": {
            "usd": 1.1483,
            "jpy": 149.93
          },
          "2022-02-16": {
            "usd": 1.1482,
            "jpy": 149.93
          }
        }
      }
    render json: @sailings.to_json
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  before_action :set_event, only: [:show]

  def index
    @upcoming = Event.where('event_date_time >= ?', Date.current).order(:event_date_time).first || Event.where(default: true).first
    @crew = Musician.where(main_page: true).order(created_at: :asc)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.save
    if @subscription.save!
      redirect_to :root, notice: "Successfully subscribed!"
    else
      redirect_to :root, error: "Error occured while subscribing! Write directly to nalcarya1881@gmail.com"
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:email, :country)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_video
    @video = Video.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def video_params
    params.require(:video).permit(:title, :youtube_link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/active_storage/blobs/_blob.html.haml
%figure{:class => "attachment attachment--#{blob.representable? ? "preview" : "file"} attachment--#{blob.filename.extension}"}
  - if blob.representable?
    = image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])
  %figcaption.attachment__caption
    - if caption = blob.try(:caption)
      = caption
    - else
      %span.attachment__name= blob.filename
      %span.attachment__size= number_to_human_size blob.byte_size

app/views/events/index.html.haml
%p nothing there yet

app/views/events/show.html.haml
%p#notice= notice
%p
  %strong Published:
  = @event.published
%p
  %strong Location:
  = @event.location.html_safe
%p
  %strong Event date time:
  = @event.event_date_time
%p
  %strong Title en:
  = @event.title_en
%p
  %strong Title ru:
  = @event.title_ru
%p
  %strong Text en:
  = @event.text_en
%p
  %strong Text ru:
  = @event.text_ru
- @event.images.each do |img|
  %td= image_tag(img)
- @event.videos.each do |v|
  - if v.youtube_link.present?
    %td= v.youtube_link.html_safe
  - elsif v.videofile.attached?
    %td= video_tag(url_for(v.videofile), controls: true)
= link_to 'Edit', edit_event_path(@event)
|
= link_to 'Back', events_path

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title The60steensclub
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/static_pages/index.html.haml
/ Welcome Section
%section
  %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark{style: 'background: black!important'}
    %a.navbar-brand{:href => "#"}
      = image_tag 'logo.png', :alt => 'Sample App', :class => 'rounded mx-auto d-block', width: 50
    %button.navbar-toggler{"aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavAltMarkup", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarNavAltMarkup.collapse.navbar-collapse
      .navbar-nav
        %a.nav-item.nav-link.active{:href => "#"}
          About
          %span.sr-only (current)
        %a.nav-item.nav-link.disabled{:href => "#"} Events
        %a.nav-item.nav-link.disabled{:href => "#"} Musicians
        %a.nav-item.nav-link.disabled{:href => "#"} Radio
    %span.navbar-text
      %a{ href: 'https://www.youtube.com/channel/UC4TqgDUrHqbOpUN80DYyhYw' }
        .fa.fa-brands.fa-youtube{style: 'color: white', height: '100px'}
      %span &#8226;
      %a{ href: 'https://www.instagram.com/60steensclub/' }
        .fa
        .fa.fa-brands.fa-instagram{style: 'color: white', height: '100px'}
      %span &#8226;
      %a{ href: 'https://vk.com/60steens.club' }
        .fa
        .fa.fa-brands.fa-vk{style: 'color: white', height: '100px'}
%section#tmWelcome.parallax-window{"data-image-src" => "#{image_url('main_img.jpg')}", "data-parallax" => "scroll"}
  .container-fluid.tm-brand-container-outer
    .row
      .col-12
        / Logo Area
        / Black transparent bg
        .mr-0.tm-bg-black-transparent.text-white.tm-brand-container-inner
          .tm-brand-container.text-center
            / %h1.tm-brand-name Mini Profile
            = image_tag('logo.png', :class => 'tm-brand-logo')
            %br
            %br
            %p.tm-brand-description.mb-0 ART ROCK 
            %p.tm-brand-description.mb-0 &#8226;
            %p.tm-brand-description.mb-0 PROGRESSIVE  
            %p.tm-brand-description.mb-0 &#8226;
            %p.tm-brand-description.mb-0 PSYCHEDELIC 

  .tm-bg-white-transparent.tm-welcome-container
    .container-fluid
      .row.h-100
        / Welcome Text
        / White transparent bg
        .col-md-7.tm-welcome-left-col
          .tm-welcome-left
            %h1.tm-welcome-title= "NEXT GIG: #{@upcoming.title_en}"
            %h3.tm-welcome-title= @upcoming.event_date_time.in_time_zone('Lisbon').strftime("%d %B %Y, %H:%m (%Z)")
            %p.pb-0{ style: 'color: black!important' }
              = @upcoming.text_en
        / Brown bg
        .col-md-5
          / .tm-welcome-right
          / %i.fas.fa-4x.fa-address-card.p-3.tm-welcome-icon
          = @upcoming.location.html_safe
/ End Welcome section
/ Portfolio section
%section#tmPortfolio
  .container-fluid
    - @crew.each do |member|
      .row
        .col-12
          .tm-portfolio-item
            / %div.tm-portfolio-name.text-white.tm-bg-green
            %div.tm-portfolio-name.tm-bg-green
              = image_tag member.main_image, alt: '', height: '100%', width: '100%', class: ''
              =#  image_tag "#{url_for(member.main_image)}", alt: '', height: '100%', width: '100%', class: ''
            .tm-portfolio-description
              %h1
                = member.name_en
              %h4
                = member.instruments
              %hr
              %p.mb-0
                = member.bio_en

/ End portfolio section
/ Contact section
#tmContact.parallax-window{"data-image-src" => "#{image_url('main_img2.jpg')}", "data-parallax" => "scroll"}
  .container-fluid
    .row
      .col-12
        .tm-contact-items-container
          .tm-contact-item
            = image_tag(@upcoming.poster, height: '100%', width: '100%')
          .tm-contact-item
            %h3
              NEXT EVENT:
            %h3
              = @upcoming.title_en
            %hr
            %h5.tm-welcome-title= @upcoming.event_date_time.in_time_zone('Lisbon').strftime("%d %B %Y, %H:%m (%Z)")
            %hr
            %p.mb-0
              = @upcoming.text_en
          .tm-contact-item{ style: 'width: 680px;' }
            = @upcoming.location.html_safe
    .row
      .col-12
        = form_with model: Subscription.new, html: {id: 'tmContactForm', class: 'tm-bg-white-transparent'} do |form|
          .form-group
            = form.text_field :email, placeholder: "Email", id: 'contact_email', type: 'email', class: 'form-control rounded-0 border-top-0 border-right-0 border-left-0', required: true
          .form-group
            = form.text_field :country, placeholder: "Select country", class: 'form-control rounded-0 border-top-0 border-right-0 border-left-0'
          .text-center
            = form.submit "Subscribe", class: 'btn tm-btn-submit rounded-0 text-white'
        - flash.each do |type, msg|
          - if type == 'notice'
            = content_tag :div, msg, class: "alert alert-success"
          - else
            = content_tag :div, msg, class: "alert alert-danger"
    / row
    .row
      %footer.col-12
        %p.text-center.tm-copyright-text
  / container
/ section

app/views/videos/_form.html.haml
= form_with(model: video, local: true) do |form|
  - if video.errors.any?
    #error_explanation
      %h2
        = pluralize(video.errors.count, "error")
        prohibited this video from being saved:
      %ul
        - video.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :youtube_link
    = form.text_area :youtube_link
  .actions
    = form.submit

app/views/videos/edit.html.haml
%h1 Editing Video
= render 'form', video: @video
= link_to 'Show', @video
|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
%p#notice= notice
%h1 Videos
%table
  %thead
    %tr
      %th Title
      %th Youtube link
      %th{:colspan => "3"}
  %tbody
    - @videos.each do |video|
      %tr
        %td= video.title
        %td= video.youtube_link
        %td= link_to 'Show', video
        %td= link_to 'Edit', edit_video_path(video)
        %td= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Video', new_video_path

app/views/videos/new.html.haml
%h1 New Video
= render 'form', video: @video
= link_to 'Back', videos_path

app/views/videos/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @video.title
%p
  %strong Youtube link:
  = @video.youtube_link
= link_to 'Edit', edit_video_path(@video)
|
= link_to 'Back', videos_path